<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Teste Suite" duration-ms="198" started-at="2018-07-18T11:21:15Z" finished-at="2018-07-18T11:21:15Z">
    <groups>
    </groups>
    <test name="Teste" duration-ms="198" started-at="2018-07-18T11:21:15Z" finished-at="2018-07-18T11:21:15Z">
      <class name="testclasses.TestNGAssert">
        <test-method status="PASS" signature="String()[pri:0, instance:testclasses.TestNGAssert@62ee68d8]" name="String" duration-ms="15" started-at="2018-07-18T11:21:15Z" finished-at="2018-07-18T11:21:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- String -->
        <test-method status="PASS" signature="array()[pri:0, instance:testclasses.TestNGAssert@62ee68d8]" name="array" duration-ms="3" started-at="2018-07-18T11:21:15Z" finished-at="2018-07-18T11:21:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- array -->
        <test-method status="PASS" signature="testeSum()[pri:0, instance:testclasses.TestNGAssert@62ee68d8]" name="testeSum" duration-ms="4" started-at="2018-07-18T11:21:15Z" finished-at="2018-07-18T11:21:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testeSum -->
      </class> <!-- testclasses.TestNGAssert -->
      <class name="dependentMethods.DependentMethods">
        <test-method status="PASS" signature="testMethod2()[pri:0, instance:dependentMethods.DependentMethods@58651fd0]" name="testMethod2" duration-ms="1" started-at="2018-07-18T11:21:15Z" finished-at="2018-07-18T11:21:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method status="FAIL" signature="testMethod1()[pri:0, instance:dependentMethods.DependentMethods@58651fd0]" name="testMethod1" duration-ms="111" started-at="2018-07-18T11:21:15Z" depends-on-methods="dependentMethods.DependentMethods.testMethod2" finished-at="2018-07-18T11:21:15Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method dependentMethods.DependentMethods.testMethod1() didn't finish within the time-out 100]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method dependentMethods.DependentMethods.testMethod1() didn't finish within the time-out 100
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
      </class> <!-- dependentMethods.DependentMethods -->
      <class name="testclasses.TestNGSoftAssert">
        <test-method status="FAIL" signature="testSum()[pri:0, instance:testclasses.TestNGSoftAssert@735b5592]" name="testSum" duration-ms="12" started-at="2018-07-18T11:21:15Z" finished-at="2018-07-18T11:21:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [2] but found [3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [2] but found [3]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testclasses.TestNGSoftAssert.testSum(TestNGSoftAssert.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSum -->
      </class> <!-- testclasses.TestNGSoftAssert -->
    </test> <!-- Teste -->
  </suite> <!-- Teste Suite -->
</testng-results>
